// Think Metric

globalThis.ingredientsDB = [
   { key: "Alfalfa",       description: "Alfalfa",                                  gramsPerCup:  33 },
   { key: "Allspice",      description: "Ground Allspice",                          gramsPerCup:  97 },
   { key: "Allspice",      description: "Whole Allspice",                           gramsPerCup: 115 },
   { key: "Almonds",       description: "Flaked Almonds",                           gramsPerCup:  90 },
   { key: "Almonds",       description: "Ground Almonds",                           gramsPerCup:  95 },
   { key: "Almonds",       description: "Sliced Almonds",                           gramsPerCup:  86 },
   { key: "Almonds",       description: "Slivered Almonds",                         gramsPerCup: 110 },
   { key: "Almonds",       description: "Whole Almonds",                            gramsPerCup: 155 },
   { key: "Apples",        description: "Chopped Apples",                           gramsPerCup: 118 },
   { key: "Apples",        description: "Dried Apples",                             gramsPerCup:  95 },
   { key: "Apples",        description: "Peeled Sliced Apples",                     gramsPerCup: 113 },
   { key: "Apples",        description: "Sliced Apples",                            gramsPerCup: 180 },
   { key: "Apples",        description: "Sliced Raw Apples",                        gramsPerCup: 110 },
   { key: "Apples",        description: "Sulfured Apples",                          gramsPerCup:  90 },
   { key: "Apricots",      description: "Chopped Apricots",                         gramsPerCup: 190 },
   { key: "Apricots",      description: "Chopped Glacé (candied) Apricots",         gramsPerCup: 225 },
   { key: "Apricots",      description: "Dried Apricots",                           gramsPerCup: 160 },
   { key: "Apricots",      description: "Sliced Raw Apricots",                      gramsPerCup: 225 },
   { key: "Arrowroot",     description: "Arrowroot",                                gramsPerCup: 227 },
   { key: "Asparagus",     description: "Canned Diced Asparagus",                   gramsPerCup: 175 },
   { key: "Asparagus",     description: "Cooked Diced Asparagus",                   gramsPerCup: 175 },
   { key: "Asparagus",     description: "Pieces of Raw Asparagus",                  gramsPerCup: 125 },
   { key: "Bacon",         description: "Diced Raw Bacon",                          gramsPerCup: 225 },
   { key: "Baking Agent",  description: "All-Purpose Baking Mix",                   gramsPerCup: 120 },
   { key: "Baking Agent",  description: "Baking Powder (leavening raising agent)",  gramsPerCup: 185 },
   { key: "Baking Agent",  description: "Baking Soda (leavening raising agent",     gramsPerCup: 255 },
   { key: "Bamboo",        description: "Bamboo Shoots",                            gramsPerCup: 268 },
   { key: "Bananas",       description: "Diced Raw Bananas",                        gramsPerCup: 200 },
   { key: "Bananas",       description: "Mashed Bananas",                           gramsPerCup: 225 },
   { key: "Bananas",       description: "Raw Mashed Bananas",                       gramsPerCup: 300 },
   { key: "Bananas",       description: "Raw Sliced Bananas",                       gramsPerCup: 225 },
   { key: "Bananas",       description: "Ripe Bananas",                             gramsPerCup: 225 },
   { key: "Bananas",       description: "Sliced Bananas",                           gramsPerCup: 178 },
   { key: "Barley",        description: "Barley Flakes",                            gramsPerCup:  92 },
   { key: "Barley",        description: "Cooked Barley",                            gramsPerCup: 215 },
   { key: "Barley",        description: "Cooked Pearled Barley",                    gramsPerCup: 157 },
   { key: "Barley",        description: "Pearl Barley",                             gramsPerCup: 200 },
   { key: "Barley",        description: "Pearled Barley",                           gramsPerCup: 213 },
   { key: "Barley",        description: "Whole Uncooked Barley",                    gramsPerCup: 184 },
   { key: "Basil",         description: "Dried Basil",                              gramsPerCup:  24 },
   { key: "Basil",         description: "Fresh Basil Leaves",                       gramsPerCup:  10 },
   { key: "Basil",         description: "Fresh Basil Leaves",                       gramsPerCup:  25, packed: true },
   { key: "Beans",         description: "Boiled Garbanzo Beans",                    gramsPerCup: 164 },
   { key: "Beans",         description: "Boiled Red Kidney Beans",                  gramsPerCup: 177 },
   { key: "Beans",         description: "Boiled White Beans",                       gramsPerCup: 179 },
   { key: "Beans",         description: "Cooked Black Fidney Beans",                gramsPerCup:  62 },
   { key: "Beans",         description: "Cooked Diced green Beans",                 gramsPerCup: 180 },
   { key: "Beans",         description: "Cooked Garbanzo Beans",                    gramsPerCup: 164 },
   { key: "Beans",         description: "Cooked Lima Beans",                        gramsPerCup:  75 },
   { key: "Beans",         description: "Cooked Red Kidney Beans",                  gramsPerCup: 177 },
   { key: "Beans",         description: "Cooked White Beans",                       gramsPerCup: 179 },
   { key: "Beans",         description: "Diced Cooked Runner Beans",                gramsPerCup: 180 },
   { key: "Beans",         description: "Diced Raw Runner Beans",                   gramsPerCup: 150 },
   { key: "Beans",         description: "Dried Beans",                              gramsPerCup: 199 },
   { key: "Beans",         description: "Dry Beans",                                gramsPerCup: 184 },
   { key: "Beans",         description: "Dry Whole Beans",                          gramsPerCup: 200 },
   { key: "Beans",         description: "Raw Diced green Beans",                    gramsPerCup: 150 },
   { key: "Beans",         description: "Raw Garbanzo Beans",                       gramsPerCup: 200 },
   { key: "Beans",         description: "Raw Mung Beans",                           gramsPerCup: 207 },
   { key: "Beans",         description: "Raw Red Fidney Beans",                     gramsPerCup: 184 },
   { key: "Beans",         description: "Raw Snap Green Beans",                     gramsPerCup: 100 },
   { key: "Beans",         description: "Sprouted Mung Beans",                      gramsPerCup: 104 },
   { key: "Beef",          description: "Cooked Beef",                              gramsPerCup: 228 },
   { key: "Beef",          description: "Cooked Diced Beef",                        gramsPerCup: 150 },
   { key: "Beef",          description: "Raw Beef",                                 gramsPerCup: 219 },
   { key: "Beef",          description: "Raw Minced Ground Beef",                   gramsPerCup: 225 },
   { key: "Beets",         description: "Cooked Sliced Diced Beets",                gramsPerCup: 200 },
   { key: "Beets",         description: "Raw Sliced Diced Grated Beets",            gramsPerCup: 150 },
   { key: "Biscuit",       description: "Mix Biscuit",                              gramsPerCup: 128 },
   { key: "Blueberries",   description: "Blueberries",                              gramsPerCup: 100 },
   { key: "Blueberries",   description: "Canned Blueberries",                       gramsPerCup: 256 },
   { key: "Blueberries",   description: "Dried Blueberries",                        gramsPerCup: 135 },
   { key: "Blueberries",   description: "Fresh Blueberries",                        gramsPerCup: 155 },
   { key: "Blueberries",   description: "Frozen Blueberries",                       gramsPerCup: 160 },
   { key: "Blueberries",   description: "Frozen Sweetened Blueberries",             gramsPerCup: 230 },
   { key: "Blueberries",   description: "Frozen Unsweetened Blueberries",           gramsPerCup: 155 },
   { key: "Blueberry",     description: "Juice Blueberry",                          gramsPerCup: 241 },
   { key: "Bran",          description: "Oat Bran",                                 gramsPerCup: 106 },
   { key: "Bran",          description: "Unsifted Bran",                            gramsPerCup:  56 },
   { key: "Bread",         description: "Bread Crumbs",                             gramsPerCup: 108 },
   { key: "Bread",         description: "Chunks of Fresh Bread",                    gramsPerCup:  50 },
   { key: "Bread",         description: "Chunks of Stale Bread",                    gramsPerCup:  50 },
   { key: "Bread",         description: "Dry Bread",                                gramsPerCup: 108 },
   { key: "Bread",         description: "Dry Crumbs Bread",                         gramsPerCup:  90 },
   { key: "Bread",         description: "Fresh Crumbs Bread",                       gramsPerCup:  50 },
   { key: "Bread",         description: "White Bread",                              gramsPerCup:  40 },
   { key: "Broccoli",      description: "Boiled Broccoli",                          gramsPerCup: 184 },
   { key: "Broccoli",      description: "Cooked Broccoli",                          gramsPerCup: 184 },
   { key: "Broccoli",      description: "Florets Fresh Raw Broccoli",               gramsPerCup: 175 },
   { key: "Broccoli",      description: "Frozen Broccoli",                          gramsPerCup: 184 },
   { key: "Broth",         description: "Beef Broth",                               gramsPerCup: 240 },
   { key: "Broth",         description: "Chicken Broth",                            gramsPerCup: 240 },
   { key: "Broth",         description: "Fish Broth",                               gramsPerCup: 244 },
   { key: "Buckwheat",     description: "Whole Buckwheat",                          gramsPerCup: 170 },
   { key: "Bulgur",        description: "Cooked Bulgur",                            gramsPerCup: 135 },
   { key: "Bulgur",        description: "Cracked Wheat Bulgur",                     gramsPerCup: 152 },
   { key: "Bulgur",        description: "Dry Bulgur",                               gramsPerCup: 140 },
   { key: "Butter",        description: "Almond Butter",                            gramsPerCup: 272 },
   { key: "Butter",        description: "Butter",                                   gramsPerCup: 225 },
   { key: "Butter",        description: "Ghee Butter",                              gramsPerCup: 176 },
   { key: "Butter",        description: "Peanut Butter",                            gramsPerCup: 270 },
   { key: "Butter",        description: "Salted Butter",                            gramsPerCup: 225 },
   { key: "Butter",        description: "Unsalted Butter",                          gramsPerCup: 225 },
   { key: "Buttermilk",    description: "Buttermilk Powder",                        gramsPerCup: 144 },
   { key: "Buttermilk",    description: "Buttermilk",                               gramsPerCup: 235 },
   { key: "Buttermilk",    description: "Dried Buttermilk",                         gramsPerCup: 114 },
   { key: "Buttermilk",    description: "Lowfat Buttermilk",                        gramsPerCup: 244 },
   { key: "Buttermilk",    description: "Whole Buttermilk",                         gramsPerCup: 244 },
   { key: "Cabbage",       description: "Cooked Chopped Cabbage",                   gramsPerCup: 225 },
   { key: "Cabbage",       description: "Raw Chopped Cabbage",                      gramsPerCup: 100 },
   { key: "Cabbage",       description: "Shredded Cabbage",                         gramsPerCup: 341 },
   { key: "Cacao",         description: "Cacao Nibs",                               gramsPerCup: 120 },
   { key: "Cacao",         description: "Raw Cacao Powder",                         gramsPerCup:  85 },
   { key: "Capers",        description: "Whole Drained Capers",                     gramsPerCup: 175 },
   { key: "Capsicum",      description: "Diced Capsicum",                           gramsPerCup: 175 },
   { key: "Caramel",       description: "Caramel Bits",                             gramsPerCup: 156 },
   { key: "Caramel",       description: "Caramel Pieces (3cm squares)",             gramsPerCup: 284 },
   { key: "Carrots",       description: "Cooked Carrots",                           gramsPerCup: 256 },
   { key: "Carrots",       description: "Cooked Sliced Carrots",                    gramsPerCup: 150 },
   { key: "Carrots",       description: "Diced Carrots",                            gramsPerCup: 142 },
   { key: "Carrots",       description: "Grated Carrots",                           gramsPerCup:  99 },
   { key: "Carrots",       description: "Puréed Carrots",                           gramsPerCup: 256 },
   { key: "Carrots",       description: "Raw Grated Carrots",                       gramsPerCup:  50 },
   { key: "Carrots",       description: "Raw Sliced Carrots",                       gramsPerCup: 150 },
   { key: "Cashews",       description: "Chopped Cashews",                          gramsPerCup: 113 },
   { key: "Cashews",       description: "Whole Cashews",                            gramsPerCup: 113 },
   { key: "Catsup",        description: "Catsup",                                   gramsPerCup: 272 },
   { key: "Cauliflower",   description: "Cauliflower Florets",                      gramsPerCup: 229 },
   { key: "Cauliflower",   description: "Cooked Cauliflower Florets",               gramsPerCup: 325 },
   { key: "Cauliflower",   description: "Raw Cauliflower",                          gramsPerCup: 110 },
   { key: "Celeriac",      description: "Cooked Diced Celeriac",                    gramsPerCup: 200 },
   { key: "Celeriac",      description: "Diced Raw Celeriac",                       gramsPerCup: 150 },
   { key: "Celeriac",      description: "Sliced Raw Celeriac",                      gramsPerCup: 150 },
   { key: "Celery",        description: "Chopped Raw Celery",                       gramsPerCup: 100 },
   { key: "Celery",        description: "Cooked Chopped Celery",                    gramsPerCup: 225 },
   { key: "Celery",        description: "Cooked Sliced Celery",                     gramsPerCup: 225 },
   { key: "Celery",        description: "Diced Celery",                             gramsPerCup: 142 },
   { key: "Celery",        description: "Sliced Raw Celery",                        gramsPerCup: 100 },
   { key: "Cereal",        description: "Bran Cereal",                              gramsPerCup:  60 },
   { key: "Cereal",        description: "Bran Flakes Cereal",                       gramsPerCup:  37 },
   { key: "Cereal",        description: "Corn Flakes Cereal",                       gramsPerCup:  25 },
   { key: "Cereal",        description: "Crushed Corn Flakes Cereal",               gramsPerCup:  75 },
   { key: "Cereal",        description: "Dry Oat Cereal",                           gramsPerCup:  80 },
   { key: "Cereal",        description: "Quick Oat Cereal",                         gramsPerCup:  80 },
   { key: "Cereal",        description: "Rice Krispies Cereal",                     gramsPerCup:  22 },
   { key: "Cheese",        description: "Colby Cheese",                             gramsPerCup: 113 },
   { key: "Cheese",        description: "Cottage Cheese",                           gramsPerCup: 220 },
   { key: "Cheese",        description: "Cream Cheese",                             gramsPerCup: 230 },
   { key: "Cheese",        description: "Crumbled Feta Cheese",                     gramsPerCup: 150 },
   { key: "Cheese",        description: "Cubed Cheddar Cheese",                     gramsPerCup: 132 },
   { key: "Cheese",        description: "Cubed Hard Cheese",                        gramsPerCup: 125 },
   { key: "Cheese",        description: "Feta Cheese",                              gramsPerCup: 114 },
   { key: "Cheese",        description: "Grated Cheddar Cheese",                    gramsPerCup: 115 },
   { key: "Cheese",        description: "Grated Colby Cheese",                      gramsPerCup: 110 },
   { key: "Cheese",        description: "Grated Hard Cheese",                       gramsPerCup: 100 },
   { key: "Cheese",        description: "Grated Jack Cheese",                       gramsPerCup: 120 },
   { key: "Cheese",        description: "Grated Mozzarella Cheese",                 gramsPerCup: 113 },
   { key: "Cheese",        description: "Grated Parmesan Cheese",                   gramsPerCup: 135 },
   { key: "Cheese",        description: "Grated Soft Cheese",                       gramsPerCup: 100 },
   { key: "Cheese",        description: "Gruyere Cheese",                           gramsPerCup: 108 },
   { key: "Cheese",        description: "Mascarpone Cheese",                        gramsPerCup: 227 },
   { key: "Cheese",        description: "Ricotta Cheese",                           gramsPerCup: 240 },
   { key: "Cheese",        description: "Shredded Cheddar Cheese",                  gramsPerCup: 113 },
   { key: "Cheese",        description: "Shredded Monterey Cheese",                 gramsPerCup: 114 },
   { key: "Cheese",        description: "Shredded Swiss Cheese",                    gramsPerCup: 108 },
   { key: "Cherries",      description: "Candied Cherries",                         gramsPerCup: 200 },
   { key: "Cherries",      description: "Chopped Glacé (candied) Cherries",         gramsPerCup:  95 },
   { key: "Cherries",      description: "Dried Cherries",                           gramsPerCup: 142 },
   { key: "Cherries",      description: "Fresh Chopped Pitted Cherries",            gramsPerCup: 160 },
   { key: "Cherries",      description: "Frozen Cherries",                          gramsPerCup: 113 },
   { key: "Cherries",      description: "Glacé (candied) Cherries",                 gramsPerCup: 190 },
   { key: "Cherries",      description: "Pitted Cherries",                          gramsPerCup: 225 },
   { key: "Chicken",       description: "Broiled Chopped Chicken Giblets",          gramsPerCup: 145 },
   { key: "Chicken",       description: "Cooked Shredded Chicken",                  gramsPerCup: 125 },
   { key: "Chicken",       description: "Fried Chopped Chicken Giblets",            gramsPerCup: 145 },
   { key: "Chickpeas",     description: "Boiled Chickpeas",                         gramsPerCup: 164 },
   { key: "Chickpeas",     description: "Cooked Chickpeas",                         gramsPerCup: 164 },
   { key: "Chickpeas",     description: "Raw Chickpeas",                            gramsPerCup: 200 },
   { key: "Chives",        description: "Dried Chopped Chives",                     gramsPerCup:  10 },
   { key: "Chives",        description: "Fresh Chives",                             gramsPerCup:  42 },
   { key: "Chives",        description: "Fresh Chopped Chives",                     gramsPerCup:  52 },
   { key: "Chocolate",     description: "Chocolate Chips",                          gramsPerCup: 175 },
   { key: "Chocolate",     description: "Chocolate Chunks",                         gramsPerCup: 170 },
   { key: "Chocolate",     description: "Chocolate Cocoa Powder",                   gramsPerCup: 110 },
   { key: "Chocolate",     description: "Chopped Chocolate",                        gramsPerCup: 170 },
   { key: "Chocolate",     description: "Grated Chocolate",                         gramsPerCup: 115 },
   { key: "Chocolate",     description: "Melted Chocolate",                         gramsPerCup: 243 },
   { key: "Chocolate",     description: "Mini Chocolate Chips",                     gramsPerCup: 177 },
   { key: "Chocolate",     description: "White Chocolate Chips",                    gramsPerCup: 170 },
   { key: "Cilantro",      description: "Raw Leaves of Cilantro",                   gramsPerCup:  16 },
   { key: "Cinnamon",      description: "Ground Cinnamon",                          gramsPerCup: 119 },
   { key: "Cloves",        description: "Ground Cloves",                            gramsPerCup:  95 },
   { key: "Cloves",        description: "Whole Cloves",                             gramsPerCup:  90 },
   { key: "Cocoa",         description: "Cocoa Powder",                             gramsPerCup:  85 },
   { key: "Cocoa",         description: "Cocoa Powder",                             gramsPerCup: 100 },
   { key: "Cocoa",         description: "Cocoa Puffs",                              gramsPerCup:  36 },
   { key: "Cocoa",         description: "Dutch-Process Cocoa Powder",               gramsPerCup: 100 },
   { key: "Cocoa",         description: "Dutch-Processed Cocoa Powder",             gramsPerCup:  85 },
   { key: "Cocoa",         description: "Unsweetened Cocoa Powder",                 gramsPerCup: 100 },
   { key: "Coconut",       description: "Coconut Cream",                            gramsPerCup: 284 },
   { key: "Coconut",       description: "Coconut Flakes",                           gramsPerCup:  60 },
   { key: "Coconut",       description: "Coconut Milk Powder",                      gramsPerCup: 114 },
   { key: "Coconut",       description: "Dessicated Coconut",                       gramsPerCup:  90 },
   { key: "Coconut",       description: "Flaked Coconut",                           gramsPerCup:  75 },
   { key: "Coconut",       description: "Grated Coconut",                           gramsPerCup:  75 },
   { key: "Coconut",       description: "Milk Coconut",                             gramsPerCup: 240 },
   { key: "Coconut",       description: "Shredded Coconut",                         gramsPerCup:  65 },
   { key: "Coconut",       description: "Sweetened Condensed Coconut Milk",         gramsPerCup: 288 },
   { key: "Coconut",       description: "Sweetened Shredded Coconut",               gramsPerCup:  85 },
   { key: "Coconut",       description: "Toasted Coconut",                          gramsPerCup:  85 },
   { key: "Coffee",        description: "Brewed Coffee",                            gramsPerCup: 240 },
   { key: "Coffee",        description: "Brewed Espresso Coffee",                   gramsPerCup: 248 },
   { key: "Coffee",        description: "Espresso Coffee Powder",                   gramsPerCup: 112 },
   { key: "Coffee",        description: "Ground Coffee",                            gramsPerCup:  90 },
   { key: "Coffee",        description: "Instant Coffee",                           gramsPerCup:  56 },
   { key: "Coriander",     description: "Chopped Coriander",                        gramsPerCup:  50 },
   { key: "Coriander",     description: "Raw Leaves of Coriander",                  gramsPerCup:  16 },
   { key: "Corn",          description: "Canned Sweet Corn",                        gramsPerCup: 250 },
   { key: "Corn",          description: "Cream Style Corn",                         gramsPerCup: 256 },
   { key: "Corn",          description: "Fresh Kernels of Corn",                    gramsPerCup: 152 },
   { key: "Corn",          description: "Fresh Sweet Corn",                         gramsPerCup: 175 },
   { key: "Corn",          description: "Frozen Corn",                              gramsPerCup: 152 },
   { key: "Corn",          description: "Frozen Whole Kernel Corn",                 gramsPerCup: 114 },
   { key: "Corn",          description: "Popped Corn (popcorn)",                    gramsPerCup:  10 },
   { key: "Corn",          description: "Raw Kernels of Corn",                      gramsPerCup: 145 },
   { key: "Corn",          description: "Sweet Yellow Corn",                        gramsPerCup: 144 },
   { key: "Corn",          description: "Syrup Corn",                               gramsPerCup: 300 },
   { key: "Cornflakes",    description: "Cornflakes",                               gramsPerCup:  28 },
   { key: "Cottage",       description: "Cheese Cottage",                           gramsPerCup: 225 },
   { key: "Couscous",      description: "Uncooked Couscous",                        gramsPerCup: 180 },
   { key: "Crab",          description: "Canned Crab",                              gramsPerCup: 135 },
   { key: "Crab",          description: "Cooked Moist Crab",                        gramsPerCup: 135 },
   { key: "Crackers",      description: "Broken Crackers",                          gramsPerCup: 175 },
   { key: "Crackers",      description: "Crushed Graham Crackers",                  gramsPerCup:  85 },
   { key: "Cranberries",   description: "Cooked Cranberries",                       gramsPerCup: 100 },
   { key: "Cranberries",   description: "Cranberries",                              gramsPerCup: 100 },
   { key: "Cranberries",   description: "Dried Cranberries",                        gramsPerCup: 115 },
   { key: "Cranberries",   description: "Fresh Cranberries",                        gramsPerCup: 100 },
   { key: "Cranberries",   description: "Frozen Cranberries",                       gramsPerCup: 100 },
   { key: "Cranberries",   description: "Raw Cranberries",                          gramsPerCup: 100 },
   { key: "Cream",         description: "Coconut Cream",                            gramsPerCup: 284 },
   { key: "Cream",         description: "Crème Fraîche Cream",                      gramsPerCup: 248 },
   { key: "Cream",         description: "Fluid Heavy Whipping Cream",               gramsPerCup: 240 },
   { key: "Cream",         description: "Fluid Light Whipping Cream",               gramsPerCup: 240 },
   { key: "Cream",         description: "Half & Half Cream",                        gramsPerCup: 227 },
   { key: "Cream",         description: "Heavy Cream",                              gramsPerCup: 230 },
   { key: "Cream",         description: "Light Cream",                              gramsPerCup: 227 },
   { key: "Cream",         description: "Reduced Fat Sour Cream",                   gramsPerCup: 191 },
   { key: "Cream",         description: "Sour Cream",                               gramsPerCup: 130 },
   { key: "Cream",         description: "Table Cream",                              gramsPerCup: 240 },
   { key: "Cream",         description: "Whipped Cream",                            gramsPerCup:  40 },
   { key: "Croutons",      description: "Seasoned Croutons",                        gramsPerCup:  40 },
   { key: "Crumbs",        description: "Biscuit Crumbs",                           gramsPerCup: 100 },
   { key: "Crumbs",        description: "Cracker Crumbs",                           gramsPerCup:  59 },
   { key: "Crumbs",        description: "Dried Bread Crumbs",                       gramsPerCup: 112 },
   { key: "Crumbs",        description: "Dry Bread Crumbs",                         gramsPerCup: 150 },
   { key: "Crumbs",        description: "Fresh Bread Crumbs",                       gramsPerCup:  70 },
   { key: "Crumbs",        description: "Fresh Cake Crumbs",                        gramsPerCup:  91 },
   { key: "Crumbs",        description: "Graham Cracker Crumbs",                    gramsPerCup:  95 },
   { key: "Crumbs",        description: "Packaged Bread Crumbs",                    gramsPerCup: 123 },
   { key: "Cucumber",      description: "Diced Raw Cucumber",                       gramsPerCup: 150 },
   { key: "Currants",      description: "Black Currants",                           gramsPerCup: 100 },
   { key: "Currants",      description: "Currants",                                 gramsPerCup: 145 },
   { key: "Currants",      description: "Dried Currants",                           gramsPerCup: 150 },
   { key: "Currants",      description: "Red Currants",                              gramsPerCup: 100 },
   { key: "Dates",         description: "Chopped Dates",                            gramsPerCup: 149 },
   { key: "Dates",         description: "Pitted Chopped Dates",                     gramsPerCup: 175 },
   { key: "Dates",         description: "Whole Dates",                              gramsPerCup: 225 },
   { key: "Dill",          description: "Dill Sprigs",                              gramsPerCup:  10 },
   { key: "Dressing",      description: "Italian Salad Dressing",                   gramsPerCup: 235 },
   { key: "Dressing",      description: "Oil and Vinegar Salad Dressing",           gramsPerCup: 250 },
   { key: "Dressing",      description: "Ranch Dressing",                           gramsPerCup: 240 },
   { key: "Egg",           description: "Whites Egg",                               gramsPerCup: 222 },
   { key: "Egg",           description: "Yokes Egg",                                gramsPerCup: 271 },
   { key: "Eggplant",      description: "Diced Raw Eggplant",                       gramsPerCup: 250 },
   { key: "Eggs",          description: "Beaten Eggs",                              gramsPerCup: 232 },
   { key: "Eggs",          description: "Chopped Hard Boiled Eggs",                 gramsPerCup: 225 },
   { key: "Fat",           description: "Bacon Fat",                                gramsPerCup: 178 },
   { key: "Fat",           description: "Beef Tallow Fat",                          gramsPerCup: 205 },
   { key: "Fat",           description: "Chicken Fat",                              gramsPerCup: 205 },
   { key: "Fat",           description: "Fat",                                      gramsPerCup: 225 },
   { key: "Fat",           description: "Shredded Suet Cooking Fat",                gramsPerCup: 125 },
   { key: "Figs",          description: "Chopped Figs",                             gramsPerCup: 150 },
   { key: "Figs",          description: "Dried Chopped Figs",                       gramsPerCup: 149 },
   { key: "Figs",          description: "Dried Figs",                               gramsPerCup: 164 },
   { key: "Fish",          description: "Drained Canned Salmon Fish",               gramsPerCup: 225 },
   { key: "Fish",          description: "Flaked Cod Fish",                          gramsPerCup: 200 },
   { key: "Fish",          description: "Flaked Haddock Fish",                      gramsPerCup: 200 },
   { key: "Fish",          description: "Flaked Salmon Fish",                       gramsPerCup: 225 },
   { key: "Fish",          description: "Flaked Tuna Fish",                         gramsPerCup: 225 },
   { key: "Flaxseed",      description: "Flaxseed",                                 gramsPerCup: 140 },
   { key: "Flour",         description: "All-Purpose Flour",                        gramsPerCup: 135 },
   { key: "Flour",         description: "All-Purpose Sifted Flour",                 gramsPerCup:  97 },
   { key: "Flour",         description: "All-Purpose Unsifted Flour",               gramsPerCup: 125 },
   { key: "Flour",         description: "All-Purpose Wheat Flour",                  gramsPerCup: 120 },
   { key: "Flour",         description: "Almond Flour",                             gramsPerCup:  95 },
   { key: "Flour",         description: "Amaranth Flour",                           gramsPerCup: 103 },
   { key: "Flour",         description: "Barley Flour",                             gramsPerCup:  85 },
   { key: "Flour",         description: "Bread Flour",                              gramsPerCup: 125 },
   { key: "Flour",         description: "Brown Rice Flour",                         gramsPerCup: 128 },
   { key: "Flour",         description: "Buckwheat Flour",                          gramsPerCup: 145 },
   { key: "Flour",         description: "Cake Flour",                               gramsPerCup: 110 },
   { key: "Flour",         description: "Chickpea Flour",                           gramsPerCup:  90 },
   { key: "Flour",         description: "Coconut Flour",                            gramsPerCup: 128 },
   { key: "Flour",         description: "Corn Flour",                               gramsPerCup: 135 },
   { key: "Flour",         description: "Defatted Soy Flour",                       gramsPerCup: 105 },
   { key: "Flour",         description: "Degermed Corn Flour",                      gramsPerCup: 126 },
   { key: "Flour",         description: "Durum Flour",                              gramsPerCup: 124 },
   { key: "Flour",         description: "First Clear Flour",                        gramsPerCup: 106 },
   { key: "Flour",         description: "Flour",                                    gramsPerCup: 125 },
   { key: "Flour",         description: "French-Style Flour",                       gramsPerCup: 120 },
   { key: "Flour",         description: "Graham Flour",                             gramsPerCup:  96 },
   { key: "Flour",         description: "Hazelnut Flour",                           gramsPerCup:  89 },
   { key: "Flour",         description: "Irish-Style Flour",                        gramsPerCup: 110 },
   { key: "Flour",         description: "Italian-Style Flour",                      gramsPerCup: 106 },
   { key: "Flour",         description: "Legume Flour",                             gramsPerCup: 131 },
   { key: "Flour",         description: "Low-Fat Soy Flour",                        gramsPerCup:  88 },
   { key: "Flour",         description: "Masa Corn Flour",                          gramsPerCup: 114 },
   { key: "Flour",         description: "Millet Flour",                             gramsPerCup: 119 },
   { key: "Flour",         description: "Oat Flour",                                gramsPerCup:  92 },
   { key: "Flour",         description: "Pasta Flour",                              gramsPerCup: 145 },
   { key: "Flour",         description: "Pastry Flour",                             gramsPerCup: 106 },
   { key: "Flour",         description: "Pizza Flour",                              gramsPerCup: 115 },
   { key: "Flour",         description: "Potato Flour",                             gramsPerCup: 175 },
   { key: "Flour",         description: "Pumpernickel Flour",                       gramsPerCup: 106 },
   { key: "Flour",         description: "Quinoa Flour",                             gramsPerCup: 110 },
   { key: "Flour",         description: "Rice Flour",                               gramsPerCup: 151 },
   { key: "Flour",         description: "Roasted Soy Flour",                        gramsPerCup:  85 },
   { key: "Flour",         description: "Rye Flour",                                gramsPerCup: 120 },
   { key: "Flour",         description: "Semolina Flour",                           gramsPerCup: 170 },
   { key: "Flour",         description: "Sieved Flour",                             gramsPerCup: 110 },
   { key: "Flour",         description: "Sifted Atta Wheat Flour",                  gramsPerCup: 150 },
   { key: "Flour",         description: "Sifted Barley Flour",                      gramsPerCup: 100 },
   { key: "Flour",         description: "Sifted Besan Flour",                       gramsPerCup: 100 },
   { key: "Flour",         description: "Sifted Cake Flour",                        gramsPerCup:  99 },
   { key: "Flour",         description: "Sifted Corn Flour",                        gramsPerCup: 125 },
   { key: "Flour",         description: "Sifted Oatmeal Flour",                     gramsPerCup: 100 },
   { key: "Flour",         description: "Sifted Potato Flour",                      gramsPerCup: 150 },
   { key: "Flour",         description: "Sifted Rice Flour",                        gramsPerCup: 150 },
   { key: "Flour",         description: "Sifted Rye Flour",                         gramsPerCup: 100 },
   { key: "Flour",         description: "Sifted Tapioca Flour",                     gramsPerCup: 125 },
   { key: "Flour",         description: "Sifted White Flour",                       gramsPerCup: 100 },
   { key: "Flour",         description: "Sifted Whole Wheat Flour",                 gramsPerCup: 150 },
   { key: "Flour",         description: "Sorghum Flour",                            gramsPerCup: 138 },
   { key: "Flour",         description: "Soy Flour",                                gramsPerCup: 120 },
   { key: "Flour",         description: "Spelt Flour",                              gramsPerCup:  99 },
   { key: "Flour",         description: "Sprouted Wheat Flour",                     gramsPerCup: 113 },
   { key: "Flour",         description: "Teff Flour",                               gramsPerCup: 135 },
   { key: "Flour",         description: "Toasted Almond Flour",                     gramsPerCup:  96 },
   { key: "Flour",         description: "Wheat Bread Flour",                        gramsPerCup: 120 },
   { key: "Flour",         description: "White Rice Flour",                         gramsPerCup: 142 },
   { key: "Flour",         description: "White Rye Flour",                          gramsPerCup: 106 },
   { key: "Flour",         description: "Whole Grain Flour",                        gramsPerCup: 113 },
   { key: "Flour",         description: "Whole Ground Soy Flour",                   gramsPerCup: 112 },
   { key: "Flour",         description: "Whole Wheat Flour",                        gramsPerCup: 125 },
   { key: "Flour",         description: "Whole Wheat Unenriched Flour",             gramsPerCup: 120 },
   { key: "Flour",         description: "Whole-Grain Corn Flour",                   gramsPerCup: 117 },
   { key: "Flour",         description: "Whole-Groat Buckwheat Flour",              gramsPerCup: 120 },
   { key: "Fruit",         description: "Candied Fruit",                            gramsPerCup: 225 },
   { key: "Fruit",         description: "Fruit Jam",                                gramsPerCup: 325 },
   { key: "Fruit",         description: "Fruit Mincemeat",                          gramsPerCup: 225 },
   { key: "Fruit",         description: "Mixed Fruit",                              gramsPerCup: 175 },
   { key: "Garlic",        description: "Flakes Garlic",                            gramsPerCup: 140 },
   { key: "Garlic",        description: "Garlic",                                   gramsPerCup: 163 },
   { key: "Garlic",        description: "Minced Garlic",                            gramsPerCup: 190 },
   { key: "Garlic",        description: "Peeled Sliced Garlic",                     gramsPerCup: 149 },
   { key: "Garlic",        description: "Raw Garlic",                               gramsPerCup: 135 },
   { key: "Gelatin",       description: "Gelatin",                                  gramsPerCup: 219 },
   { key: "Ginger",        description: "Chunks of Crystallized Ginger",            gramsPerCup: 241 },
   { key: "Ginger",        description: "Crystal Ginger",                           gramsPerCup: 225 },
   { key: "Ginger",        description: "Crystallized Ginger",                      gramsPerCup: 184 },
   { key: "Ginger",        description: "Fresh Chopped Ginger",                     gramsPerCup:  50 },
   { key: "Ginger",        description: "Fresh Ginger",                             gramsPerCup: 231 },
   { key: "Ginger",        description: "Fresh Sliced Ginger",                      gramsPerCup: 228 },
   { key: "Ginger",        description: "Ground Ginger",                            gramsPerCup: 123 },
   { key: "Granola",       description: "Granola",                                  gramsPerCup: 113 },
   { key: "Grape Nuts",    description: "Grape Nutes",                              gramsPerCup: 115 },
   { key: "Grapefruit",    description: "Segments of Peeled Grapefruit",            gramsPerCup: 225 },
   { key: "Grapes",        description: "Halved Pitted Grapes",                     gramsPerCup: 175 },
   { key: "Grapes",        description: "Whole Grapes",                             gramsPerCup: 100 },
   { key: "Gravy",         description: "Canned Beef Gravy",                        gramsPerCup: 240 },
   { key: "Gravy",         description: "Canned Chicken Gravy",                     gramsPerCup: 240 },
   { key: "Gravy",         description: "Gravy",                                    gramsPerCup: 240 },
   { key: "Groats",        description: "Buckwheat Groats",                         gramsPerCup: 170 },
   { key: "Groats",        description: "Cooked Buckwheat Groats",                  gramsPerCup: 198 },
   { key: "Groats",        description: "Roasted Buckwheat Groats",                 gramsPerCup: 198 },
   { key: "Gumdrops",      description: "Gumdrops",                                 gramsPerCup: 162 },
   { key: "Ham",           description: "Cooked Diced Ham",                         gramsPerCup: 150 },
   { key: "Hazelnuts",     description: "Chopped Hazelnuts",                        gramsPerCup: 175 },
   { key: "Hazelnuts",     description: "Ground Hazelnuts",                         gramsPerCup: 100 },
   { key: "Hazelnuts",     description: "Whole Hazelnuts",                          gramsPerCup: 155 },
   { key: "Honey",         description: "Honey",                                    gramsPerCup: 340 },
   { key: "Ice",           description: "Crushed Ice",                              gramsPerCup: 140 },
   { key: "Ice",           description: "Dry Ice",                                  gramsPerCup: 200 },
   { key: "Ice",           description: "Ice Cream",                                gramsPerCup: 135 },
   { key: "Ice",           description: "Solid Ice",                                gramsPerCup: 217 },
   { key: "Jam",           description: "Fruit Jam",                                gramsPerCup: 330 },
   { key: "Juice",         description: "Concentrated Apple Juice",                 gramsPerCup: 280 },
   { key: "Juice",         description: "Cranberry Juice",                          gramsPerCup: 249 },
   { key: "Juice",         description: "Fresh Citrus Fruit Juice",                 gramsPerCup: 241 },
   { key: "Juice",         description: "Freshly Squeezed Lemon Juice",             gramsPerCup: 248 },
   { key: "Juice",         description: "Freshly Squeezed Lime Juice",              gramsPerCup: 248 },
   { key: "Juice",         description: "Lemon Juice",                              gramsPerCup: 224 },
   { key: "Juice",         description: "Pineapple Juice",                          gramsPerCup: 248 },
   { key: "Juice",         description: "Spiced Tomato Juice",                      gramsPerCup: 248 },
   { key: "Kasha",         description: "Kasha Grain",                              gramsPerCup: 170 },
   { key: "Kiwifruit",     description: "Fresh Kiwifruit",                          gramsPerCup: 180 },
   { key: "Lamb",          description: "Diced Cooked Lamb",                        gramsPerCup: 150 },
   { key: "Lamb",          description: "Ground Raw Lamb",                          gramsPerCup: 225 },
   { key: "Lamb",          description: "Shredded Cooked Lamb",                     gramsPerCup: 150 },
   { key: "Lard",          description: "Lard",                                     gramsPerCup: 215 },
   { key: "Leeks",         description: "Diced Leeks",                              gramsPerCup:  92 },
   { key: "Lemon",         description: "Grated Lemon Rind",                        gramsPerCup: 149 },
   { key: "Lemon",         description: "Segments of Peeled Lemon",                 gramsPerCup: 225 },
   { key: "Lentils",       description: "Cooked Lentils",                           gramsPerCup:  75 },
   { key: "Lentils",       description: "Dry Lentils",                              gramsPerCup: 200 },
   { key: "Lentils",       description: "Lentils",                                  gramsPerCup: 203 },
   { key: "Lentils",       description: "Sprouted Lentils",                         gramsPerCup:  77 },
   { key: "Lettuce",       description: "Chopped Lettuce",                          gramsPerCup:  75 },
   { key: "Lettuce",       description: "Shredded Lettuce",                         gramsPerCup:  75 },
   { key: "Lily",          description: "Dried Lily Buds",                          gramsPerCup:  39 },
   { key: "Lobster",       description: "Cooked Moist Lobster",                     gramsPerCup: 145 },
   { key: "Margarine",     description: "Margarine",                                gramsPerCup: 225 },
   { key: "Margarine",     description: "Salted Margarine",                         gramsPerCup: 227 },
   { key: "Margarine",     description: "Unsalted Margarine",                       gramsPerCup: 227 },
   { key: "Marshmallows",  description: "Marshmallows",                             gramsPerCup:  47 },
   { key: "Marshmallows",  description: "Mini Marshmallows",                        gramsPerCup:  43 },
   { key: "Marshmallows",  description: "Small Marshmallows",                       gramsPerCup:  48 },
   { key: "Marzipan",      description: "Marzipan",                                 gramsPerCup: 290 },
   { key: "Mayonnaise",    description: "Mayonnaise",                               gramsPerCup: 220 },
   { key: "Meal",          description: "Almond Meal",                              gramsPerCup:  85 },
   { key: "Meal",          description: "Blue Corn Meal",                           gramsPerCup: 123 },
   { key: "Meal",          description: "Corn Meal",                                gramsPerCup: 145 },
   { key: "Meal",          description: "Degermed Corn Meal",                       gramsPerCup: 138 },
   { key: "Meal",          description: "Flax Meal",                                gramsPerCup: 100 },
   { key: "Meal",          description: "Pecan Meal",                               gramsPerCup:  80 },
   { key: "Meal",          description: "Sifted Corn Meal",                         gramsPerCup: 150 },
   { key: "Meal",          description: "Whole Grain Corn Meal",                    gramsPerCup: 138 },
   { key: "Meal",          description: "Yellow Corn Meal",                         gramsPerCup: 156 },
   { key: "Meringue",      description: "Meringue Powder",                          gramsPerCup: 172 },
   { key: "Milk",          description: "Condensed Sweetened Milk",                 gramsPerCup: 305 },
   { key: "Milk",          description: "Dry Milk Powder",                          gramsPerCup: 125 },
   { key: "Milk",          description: "Dry Milk",                                 gramsPerCup: 127 },
   { key: "Milk",          description: "Dry Powdered Nonfat Milk",                 gramsPerCup: 112 },
   { key: "Milk",          description: "Dry Powdered Whole Milk",                  gramsPerCup: 100 },
   { key: "Milk",          description: "Evaporated Milk",                          gramsPerCup: 225 },
   { key: "Milk",          description: "Fresh Milk",                               gramsPerCup: 227 },
   { key: "Milk",          description: "Lowfat Milk",                              gramsPerCup: 244 },
   { key: "Milk",          description: "Milk",                                     gramsPerCup: 245 },
   { key: "Milk",          description: "Powdered Milk",                            gramsPerCup: 118 },
   { key: "Milk",          description: "Skim Milk",                                gramsPerCup: 244 },
   { key: "Milk",          description: "Sweetened Almond Milk",                    gramsPerCup: 244 },
   { key: "Milk",          description: "Sweetened Condensed Milk",                 gramsPerCup: 312 },
   { key: "Milk",          description: "Unsweetened Almond Milk",                  gramsPerCup: 244 },
   { key: "Milk",          description: "Whole Milk",                               gramsPerCup: 245 },
   { key: "Millet",        description: "Whole Millet",                             gramsPerCup: 206 },
   { key: "Mint",          description: "Fresh Chopped Mint",                       gramsPerCup:  25 },
   { key: "Miso",          description: "Miso Paste",                               gramsPerCup: 275 },
   { key: "Molasses",      description: "Molasses",                                 gramsPerCup: 335 },
   { key: "Mushrooms",     description: "Button Mushrooms",                         gramsPerCup: 110 },
   { key: "Mushrooms",     description: "Chinese Black Mushrooms",                  gramsPerCup:  52 },
   { key: "Mushrooms",     description: "Chopped Mushrooms",                        gramsPerCup:  77 },
   { key: "Mushrooms",     description: "Fresh Chopped Mushrooms",                  gramsPerCup: 100 },
   { key: "Mushrooms",     description: "Fresh Sliced Mushrooms",                   gramsPerCup:  75 },
   { key: "Mushrooms",     description: "Fresh Whole Mushrooms",                    gramsPerCup: 125 },
   { key: "Mushrooms",     description: "Sliced Mushrooms",                         gramsPerCup:  65 },
   { key: "Mushrooms",     description: "Whole Mushrooms",                          gramsPerCup:  59 },
   { key: "Mushrooms",     description: "Wood Ear Mushrooms",                       gramsPerCup:  98 },
   { key: "Mustard",       description: "Dry Mustard",                              gramsPerCup: 114 },
   { key: "Mustard",       description: "Mustard Seed",                             gramsPerCup: 149 },
   { key: "Mustard",       description: "Prepared Mustard",                         gramsPerCup: 250 },
   { key: "Nectarines",    description: "Slices of Peeled Nectarines",              gramsPerCup: 225 },
   { key: "Noodles",       description: "Cooked Noodles",                           gramsPerCup: 150 },
   { key: "Noodles",       description: "Dry Chow Mein Noodles",                    gramsPerCup:  56 },
   { key: "Noodles",       description: "Dry Egg Noodles",                          gramsPerCup:  38 },
   { key: "Noodles",       description: "UnCooked Noodles",                         gramsPerCup:  75 },
   { key: "Nuts",          description: "Chopped Cashew Nuts",                      gramsPerCup: 150 },
   { key: "Nuts",          description: "Chopped Nuts",                             gramsPerCup: 150 },
   { key: "Nuts",          description: "Chopped Pistachio Nuts",                   gramsPerCup: 100 },
   { key: "Nuts",          description: "Ground Nuts",                              gramsPerCup: 120 },
   { key: "Nuts",          description: "Nutella Hazelnut Cocoa Spread",            gramsPerCup: 298 },
   { key: "Nuts",          description: "Pine Nuts",                                gramsPerCup: 130 },
   { key: "Nuts",          description: "Pistachio Paste",                          gramsPerCup: 312 },
   { key: "Nuts",          description: "Shelled Pistachio Nuts",                   gramsPerCup: 120 },
   { key: "Nuts",          description: "Whole Brazil Nuts",                        gramsPerCup: 153 },
   { key: "Nuts",          description: "Whole Cashew Nuts",                        gramsPerCup: 150 },
   { key: "Nuts",          description: "Whole Macadamia Nuts",                     gramsPerCup: 149 },
   { key: "Nuts",          description: "Whole Pistachio Nuts",                     gramsPerCup: 150 },
   { key: "Oats",          description: "Oat Bran",                                 gramsPerCup:  80 },
   { key: "Oats",          description: "Oatmeal",                                  gramsPerCup:  85 },
   { key: "Oats",          description: "Oats",                                     gramsPerCup:  97 },
   { key: "Oats",          description: "Old Fashioned Rolled Oats",                gramsPerCup:  95 },
   { key: "Oats",          description: "Rolled Oats",                              gramsPerCup:  82 },
   { key: "Oats",          description: "Steel-Cut Oats",                           gramsPerCup: 150 },
   { key: "Oats",          description: "Uncooked Oats",                            gramsPerCup:  85 },
   { key: "Oats",          description: "Uncooked Rolled Oats",                     gramsPerCup: 100 },
   { key: "Oil",           description: "Almond Oil",                               gramsPerCup: 218 },
   { key: "Oil",           description: "Anhydrous Butter Oil",                     gramsPerCup: 225 },
   { key: "Oil",           description: "Avogado Oil",                              gramsPerCup: 218 },
   { key: "Oil",           description: "Canola Oil",                               gramsPerCup: 218 },
   { key: "Oil",           description: "Castor Oil",                               gramsPerCup: 223 },
   { key: "Oil",           description: "Cocoa Butter Oil",                         gramsPerCup: 218 },
   { key: "Oil",           description: "Coconut Oil",                              gramsPerCup: 220 },
   { key: "Oil",           description: "Cooking Oil",                              gramsPerCup: 227 },
   { key: "Oil",           description: "Corn Oil",                                 gramsPerCup: 224 },
   { key: "Oil",           description: "Cottonseed Oil",                           gramsPerCup: 218 },
   { key: "Oil",           description: "Fish Oil",                                 gramsPerCup: 218 },
   { key: "Oil",           description: "Flaxseed Oil",                             gramsPerCup: 218 },
   { key: "Oil",           description: "Grapeseed Oil",                            gramsPerCup: 218 },
   { key: "Oil",           description: "Olive Oil",                                gramsPerCup: 215 },
   { key: "Oil",           description: "Palm Oil",                                 gramsPerCup: 215 },
   { key: "Oil",           description: "Peanut Oil",                               gramsPerCup: 216 },
   { key: "Oil",           description: "Sesame Oil",                               gramsPerCup: 219 },
   { key: "Oil",           description: "Soybean Oil",                              gramsPerCup: 216 },
   { key: "Oil",           description: "Sunflower Oil",                            gramsPerCup: 218 },
   { key: "Oil",           description: "Vegetable Oil",                            gramsPerCup: 215 },
   { key: "Okra",          description: "Raw Okra",                                 gramsPerCup:  97 },
   { key: "Olives",        description: "Chopped Olives",                           gramsPerCup: 182 },
   { key: "Olives",        description: "Sliced Olives",                            gramsPerCup: 142 },
   { key: "Onion",         description: "Chopped Onion",                            gramsPerCup: 150 },
   { key: "Onion",         description: "Minced Onion",                             gramsPerCup: 199 },
   { key: "Onion",         description: "Sliced Onion",                             gramsPerCup: 132 },
   { key: "Onions",        description: "Chopped Onions",                           gramsPerCup: 160 },
   { key: "Onions",        description: "Chopped Raw Onions",                       gramsPerCup: 150 },
   { key: "Onions",        description: "Fresh Diced Onions",                       gramsPerCup: 142 },
   { key: "Onions",        description: "Sliced Onions",                            gramsPerCup: 115 },
   { key: "Onions",        description: "Sliced Raw Onions",                        gramsPerCup: 100 },
   { key: "Orange",        description: "Grated Orange Rind",                       gramsPerCup:  90 },
   { key: "Orange",        description: "Segments of Peeled Orange",                gramsPerCup: 225 },
   { key: "Oysters",       description: "Raw Oysters",                              gramsPerCup: 235 },
   { key: "Pancake",       description: "Pancake Mix",                              gramsPerCup: 142 },
   { key: "Paprika",       description: "Paprika",                                  gramsPerCup: 117 },
   { key: "Parsley",       description: "Dried Parsley",                            gramsPerCup:  26 },
   { key: "Parsley",       description: "Fresh Coarsely Chopped Parsley",           gramsPerCup:  25 },
   { key: "Parsley",       description: "Fresh Parsley",                            gramsPerCup:  45 },
   { key: "Pasta",         description: "Cooked Macaroni Pasta",                    gramsPerCup: 200 },
   { key: "Pasta",         description: "Dry Elbows Pasta",                         gramsPerCup: 122 },
   { key: "Pasta",         description: "Dry Farfalle (Bow Tie Pasta)",             gramsPerCup:  81 },
   { key: "Pasta",         description: "Dry Lasagna Pasta",                        gramsPerCup:  90 },
   { key: "Pasta",         description: "Dry Macaroni Pasta",                       gramsPerCup: 100 },
   { key: "Pasta",         description: "Dry Penne Pasta",                          gramsPerCup:  95 },
   { key: "Pasta",         description: "Dry Rotini Pasta",                         gramsPerCup:  96 },
   { key: "Pasta",         description: "Dry Shells Pasta",                         gramsPerCup:  64 },
   { key: "Pasta",         description: "Dry Spaghetti Pasta",                      gramsPerCup:  91 },
   { key: "Pasta",         description: "Egg noodles Pasta",                        gramsPerCup:  92 },
   { key: "Pasta",         description: "Macaroni Pasta",                           gramsPerCup: 118 },
   { key: "Pasta",         description: "Short Cut Cooked Pasta",                   gramsPerCup: 200 },
   { key: "Pasta",         description: "Short Cut Dry Pasta",                      gramsPerCup: 100 },
   { key: "Pasta",         description: "Uncooked Spaghetti Pasta",                 gramsPerCup: 119 },
   { key: "Paste",         description: "Almond Paste",                             gramsPerCup: 259 },
   { key: "Peaches",       description: "Fresh Sliced Peaches",                     gramsPerCup: 225 },
   { key: "Peaches",       description: "Peeled Diced Peaches",                     gramsPerCup: 170 },
   { key: "Peanuts",       description: "Chopped Peanuts",                          gramsPerCup: 140 },
   { key: "Peanuts",       description: "Creamy Peanut Butter",                     gramsPerCup: 256 },
   { key: "Peanuts",       description: "Crunchy Peanut Butter",                    gramsPerCup: 256 },
   { key: "Peanuts",       description: "Oil Roasted Peanuts",                      gramsPerCup: 151 },
   { key: "Peanuts",       description: "Shelled Peanuts",                          gramsPerCup: 150 },
   { key: "Peanuts",       description: "Whole Shelled Peanuts",                    gramsPerCup: 142 },
   { key: "Pears",         description: "Drained and Diced Canned Pears",           gramsPerCup: 175 },
   { key: "Pears",         description: "Fresh Peeled and Sliced Pears",            gramsPerCup: 225 },
   { key: "Pears",         description: "Peeled Diced Pears",                       gramsPerCup: 163 },
   { key: "Peas",          description: "Cooked Split Peas",                        gramsPerCup: 100 },
   { key: "Peas",          description: "Dry Split Peas",                           gramsPerCup: 225 },
   { key: "Peas",          description: "Fresh Shelled Green Peas",                 gramsPerCup: 150 },
   { key: "Peas",          description: "Frozen Shelled Green Peas",                gramsPerCup: 150 },
   { key: "Peas",          description: "Raw Green Peas",                           gramsPerCup: 145 },
   { key: "Peas",          description: "Split Peas",                               gramsPerCup: 199 },
   { key: "Peas",          description: "Uncooked Peas",                            gramsPerCup: 153 },
   { key: "Pecan",         description: "Nutmeat Pecan",                            gramsPerCup: 113 },
   { key: "Pecans",        description: "Chopped Pecans",                           gramsPerCup: 120 },
   { key: "Pecans",        description: "Diced Pecans",                             gramsPerCup: 114 },
   { key: "Pecans",        description: "Ground Pecans",                            gramsPerCup: 101 },
   { key: "Pecans",        description: "Nuts Shelled Chopped Pecans",              gramsPerCup: 125 },
   { key: "Pecans",        description: "Nuts Shelled Halved Pecans",               gramsPerCup: 100 },
   { key: "Pecans",        description: "Shelled Pecans",                           gramsPerCup: 123 },
   { key: "Peel",          description: "Candied Lemon Peel",                       gramsPerCup: 137 },
   { key: "Peel",          description: "Candied Orange Peel",                      gramsPerCup: 127 },
   { key: "Pepper",        description: "Black Peppercorns",                        gramsPerCup: 136 },
   { key: "Pepper",        description: "Ground Black Pepper",                      gramsPerCup: 134 },
   { key: "Pepper",        description: "Lemon Pepper Seasoning",                   gramsPerCup: 150 },
   { key: "Pepper",        description: "White Peppercorns",                        gramsPerCup: 149 },
   { key: "Peppers",       description: "Bell Peppers",                             gramsPerCup: 115 },
   { key: "Peppers",       description: "Chopped Bell Peppers",                     gramsPerCup: 175 },
   { key: "Peppers",       description: "Chopped Chili Peppers",                    gramsPerCup: 172 },
   { key: "Peppers",       description: "Diced Sweet Peppers",                      gramsPerCup: 175 },
   { key: "Peppers",       description: "Fresh Bell Peppers",                       gramsPerCup: 142 },
   { key: "Pesto",         description: "Basil Pesto",                              gramsPerCup: 224 },
   { key: "Pimento",       description: "Chopped Pimento",                          gramsPerCup: 175 },
   { key: "Pineapple",     description: "Canned Diced Pineapple",                   gramsPerCup: 170 },
   { key: "Pineapple",     description: "Chopped Glacé (candied) Pineapple",        gramsPerCup: 225 },
   { key: "Pineapple",     description: "Crushed Drained Pineapple",                gramsPerCup: 256 },
   { key: "Pineapple",     description: "Crushed Pineapple",                        gramsPerCup: 225 },
   { key: "Pineapple",     description: "Dried Pineapple",                          gramsPerCup: 142 },
   { key: "Pineapple",     description: "Fresh Cubed Pineapple",                    gramsPerCup: 200 },
   { key: "Pineapple",     description: "Fresh Diced Pineapple",                    gramsPerCup: 170 },
   { key: "Plums",         description: "Fresh stoned Plums",                       gramsPerCup: 175 },
   { key: "Pork",          description: "Chopped Cooked Pork",                      gramsPerCup: 140 },
   { key: "Pork",          description: "Raw Minced Ground Pork",                   gramsPerCup: 225 },
   { key: "Potatoes",      description: "Cooked Diced Potatoes",                    gramsPerCup: 325 },
   { key: "Potatoes",      description: "Cooked Mashed Potatoes",                   gramsPerCup: 325 },
   { key: "Potatoes",      description: "Cooked Mashed Sweet Potatoes",             gramsPerCup: 200 },
   { key: "Potatoes",      description: "Cooked Sweet Potatoes",                    gramsPerCup: 239 },
   { key: "Potatoes",      description: "Diced Cooked Potatoes",                    gramsPerCup: 203 },
   { key: "Potatoes",      description: "Diced Raw Potatoes",                       gramsPerCup: 225 },
   { key: "Potatoes",      description: "Mashed Potatoes",                          gramsPerCup: 213 },
   { key: "Potatoes",      description: "Mashed Sweet Potatoes",                    gramsPerCup: 240 },
   { key: "Potatoes",      description: "Raw Sliced Potatoes",                      gramsPerCup: 179 },
   { key: "Potatoes",      description: "Raw Sliced Sweet Potatoes",                gramsPerCup: 150 },
   { key: "Potatoes",      description: "Raw Sweet Potatoes",                       gramsPerCup: 181 },
   { key: "Prawns",        description: "Cooked Shelled Prawns",                    gramsPerCup: 325 },
   { key: "Prunes",        description: "Cooked Stoned Prunes",                     gramsPerCup: 150 },
   { key: "Prunes",        description: "Dried Prunes",                             gramsPerCup: 140 },
   { key: "Pumpkin",       description: "Canned Pumpkin",                           gramsPerCup: 245 },
   { key: "Pumpkin",       description: "Cooked Mashed Pumpkin",                    gramsPerCup: 225 },
   { key: "Pumpkin",       description: "Cooked Pumpkin",                           gramsPerCup: 182 },
   { key: "Pumpkin",       description: "Pumpkin Purée",                            gramsPerCup: 245 },
   { key: "Pumpkin",       description: "Raw 3cm Cubes Pumpkin",                    gramsPerCup: 116 },
   { key: "Pumpkin",       description: "Sliced Cooked Pumpkin",                    gramsPerCup: 150 },
   { key: "Purée",         description: "Pumpkin Purée",                            gramsPerCup: 227 },
   { key: "Purée",         description: "Tomato Purée",                             gramsPerCup: 250 },
   { key: "Quince",        description: "Fresh Stoned Quince",                      gramsPerCup: 175 },
   { key: "Quinoa",        description: "Cooked Quinoa",                            gramsPerCup: 184 },
   { key: "Quinoa",        description: "Whole Quinoa",                             gramsPerCup: 177 },
   { key: "Raisins",       description: "Cooked Raisins",                           gramsPerCup: 200 },
   { key: "Raisins",       description: "Dark Seedless Raisins",                    gramsPerCup: 146 },
   { key: "Raisins",       description: "Dark Seedless Raisins",                    gramsPerCup: 165, packed: true },
   { key: "Raisins",       description: "Dried Raisins",                            gramsPerCup: 150 },
   { key: "Raisins",       description: "Dry Sultana Raisins",                      gramsPerCup: 150 },
   { key: "Raisins",       description: "Raisins",                                  gramsPerCup: 149 },
   { key: "Raisins",       description: "Raisins",                                  gramsPerCup: 170, packed: true },
   { key: "Raisins",       description: "Seedless Raisins",                         gramsPerCup: 142 },
   { key: "Raisins",       description: "Sultana Raisins",                          gramsPerCup: 175 },
   { key: "Raspberries",   description: "Fresh Raspberries",                        gramsPerCup: 125 },
   { key: "Rhubarb",       description: "Pieces of Fresh Rhubarb",                  gramsPerCup: 100 },
   { key: "Rhubarb",       description: "Thick Sliced (1cm) Rhubarb",               gramsPerCup: 120 },
   { key: "Rice",          description: "Cooked Brown Rice",                        gramsPerCup: 170 },
   { key: "Rice",          description: "Cooked Long-grain Brown Rice",             gramsPerCup: 195 },
   { key: "Rice",          description: "Cooked Long-grain White Rice",             gramsPerCup: 158 },
   { key: "Rice",          description: "Cooked Rice",                              gramsPerCup: 250 },
   { key: "Rice",          description: "Cooked White Rice",                        gramsPerCup: 174 },
   { key: "Rice",          description: "Cooked Wild Rice",                         gramsPerCup: 164 },
   { key: "Rice",          description: "Dry Long Grain Rice",                      gramsPerCup: 198 },
   { key: "Rice",          description: "Puffed Rice",                              gramsPerCup:  25 },
   { key: "Rice",          description: "Raw Long-Grain White Rice",                gramsPerCup: 185 },
   { key: "Rice",          description: "Raw Rice",                                 gramsPerCup: 225 },
   { key: "Rice",          description: "Raw White Rice",                           gramsPerCup: 200 },
   { key: "Rice",          description: "Raw Wild Rice",                            gramsPerCup: 160 },
   { key: "Rice",          description: "Rice Crispies",                            gramsPerCup:  25 },
   { key: "Rice",          description: "Steamed Rice",                             gramsPerCup: 161 },
   { key: "Rice",          description: "Wild Rice",                                gramsPerCup: 142 },
   { key: "Root",          description: "3cm Pieces Raw Burdock Root",              gramsPerCup: 118 },
   { key: "Rutabaga",      description: "Diced Raw Rutabaga",                       gramsPerCup: 150 },
   { key: "Rutabaga",      description: "Mashed Cooked Rutabaga",                   gramsPerCup: 200 },
   { key: "Rye",           description: "Chopped Rye",                              gramsPerCup: 120 },
   { key: "Rye",           description: "Cracked Rye",                              gramsPerCup: 120 },
   { key: "Rye",           description: "Rye Flakes",                               gramsPerCup: 124 },
   { key: "Salt",          description: "Coarse Himalayan Pink Salt",               gramsPerCup: 195 },
   { key: "Salt",          description: "Coarse Sea Salt",                          gramsPerCup: 195 },
   { key: "Salt",          description: "Fine Sea Salt",                            gramsPerCup: 295 },
   { key: "Salt",          description: "Fleur de Sel (flower of salt)",            gramsPerCup: 165 },
   { key: "Salt",          description: "Garlic Salt",                              gramsPerCup: 165 },
   { key: "Salt",          description: "Kosher Salt",                              gramsPerCup: 225 },
   { key: "Salt",          description: "Popcorn Salt",                             gramsPerCup: 325 },
   { key: "Salt",          description: "Rock Salt (cooking salt)",                 gramsPerCup: 195 },
   { key: "Salt",          description: "Salt Powder (flour salt)",                 gramsPerCup: 325 },
   { key: "Salt",          description: "Sea Salt Flakes",                          gramsPerCup: 165 },
   { key: "Salt",          description: "Table Salt",                               gramsPerCup: 265 },
   { key: "Sauce",         description: "Alfredo Sauce",                            gramsPerCup: 260 },
   { key: "Sauce",         description: "Apple Sauce with Salt",                    gramsPerCup: 255 },
   { key: "Sauce",         description: "Apple Sauce without Salt",                 gramsPerCup: 248 },
   { key: "Sauce",         description: "Apple Sauce",                              gramsPerCup: 255 },
   { key: "Sauce",         description: "Cheese Sauce",                             gramsPerCup: 243 },
   { key: "Sauce",         description: "Ketchup Tomato Sauce",                     gramsPerCup: 245 },
   { key: "Sauce",         description: "Marinara Pasta Sauce",                     gramsPerCup: 264 },
   { key: "Sauce",         description: "Pizza Sauce",                              gramsPerCup: 228 },
   { key: "Sauce",         description: "Salsa Sauce",                              gramsPerCup: 256 },
   { key: "Sauce",         description: "Tomato Sauce",                             gramsPerCup: 257 },
   { key: "Sauerkraut",    description: "Sauerkraut",                               gramsPerCup: 150 },
   { key: "Scallions",     description: "Green Onion Scallions",                    gramsPerCup:  49 },
   { key: "Scallions",     description: "Sliced Scallions",                         gramsPerCup:  64 },
   { key: "Seeds",         description: "Caraway Seeds",                            gramsPerCup: 144 },
   { key: "Seeds",         description: "Celery Seeds",                             gramsPerCup: 123 },
   { key: "Seeds",         description: "Poppy Seeds",                              gramsPerCup: 135 },
   { key: "Seeds",         description: "Sesame Seeds",                             gramsPerCup: 155 },
   { key: "Seeds",         description: "Sunflower Seeds",                          gramsPerCup: 140 },
   { key: "Shallots",      description: "Peeled Sliced Shallots",                   gramsPerCup: 156 },
   { key: "Shallots",      description: "Raw Chopped Shallots",                     gramsPerCup: 150 },
   { key: "Shallots",      description: "Raw Sliced Shallots",                      gramsPerCup: 100 },
   { key: "Shallots",      description: "Shallots",                                 gramsPerCup: 243 },
   { key: "Sherbet",       description: "Sherbet",                                  gramsPerCup: 175 },
   { key: "Shortening",    description: "Melted Shortening",                        gramsPerCup: 210 },
   { key: "Shortening",    description: "Shortening Vegetable",                     gramsPerCup: 190 },
   { key: "Shortening",    description: "Shortening",                               gramsPerCup: 225 },
   { key: "Shortening",    description: "Solid Shortening",                         gramsPerCup: 218 },
   { key: "Shortening",    description: "Vegetable Shortening",                     gramsPerCup: 190 },
   { key: "Shrimp",        description: "Canned Shrimp",                            gramsPerCup: 135 },
   { key: "Shrimp",        description: "Cooked Shelled Shrimp",                    gramsPerCup: 325 },
   { key: "Soup",          description: "Condensed Cream of Mushroom Soup",         gramsPerCup: 250 },
   { key: "Soup",          description: "Cream of Mushroom Soup",                   gramsPerCup: 250 },
   { key: "Soup",          description: "Tomato Soup",                              gramsPerCup: 244 },
   { key: "Sour",          description: "Cream Sour",                               gramsPerCup: 227 },
   { key: "Soy",           description: "Shoyu (Wheat) Soy Sauce",                  gramsPerCup: 257 },
   { key: "Soy",           description: "Tamari Soy Sauce",                         gramsPerCup: 286 },
   { key: "Soybeans",      description: "Cooked Soybeans",                          gramsPerCup:  75 },
   { key: "Soybeans",      description: "Dry Soybeans",                             gramsPerCup: 200 },
   { key: "Spaghetti",     description: "Cooked Spaghetti",                         gramsPerCup:  50 },
   { key: "Spaghetti",     description: "Dry Spaghetti",                            gramsPerCup: 100 },
   { key: "Spinach",       description: "Raw Spinach",                              gramsPerCup: 225 },
   { key: "Spread",        description: "Cream Cheese Spread",                      gramsPerCup: 240 },
   { key: "Sprouts",       description: "Bean Sprouts",                             gramsPerCup: 100 },
   { key: "Squash",        description: "Mashed Cooked Winter Squash",              gramsPerCup: 450 },
   { key: "Squash",        description: "Sliced Cooked Squash",                     gramsPerCup: 150 },
   { key: "Squash",        description: "Sliced Cooked Summer Squash",              gramsPerCup: 125 },
   { key: "Starch",        description: "Corn Starch",                              gramsPerCup: 145 },
   { key: "Starch",        description: "Potato Starch",                            gramsPerCup: 152 },
   { key: "Starch",        description: "Tapioca Starch",                           gramsPerCup: 113 },
   { key: "Strawberries",  description: "Fresh Sliced Strawberries",                gramsPerCup: 167 },
   { key: "Strawberries",  description: "Frozen Unsweetened Strawberries",          gramsPerCup: 149 },
   { key: "Strawberries",  description: "Halved Fresh Strawberries",                gramsPerCup: 200 },
   { key: "Strawberries",  description: "Sliced Fresh Strawberries",                gramsPerCup: 200 },
   { key: "Strawberries",  description: "Strawberries",                             gramsPerCup: 149 },
   { key: "Sugar",         description: "Brown Sugar",                              gramsPerCup: 170 },
   { key: "Sugar",         description: "Brown Sugar",                              gramsPerCup: 215, packed: true },
   { key: "Sugar",         description: "Castor Sugar",                             gramsPerCup: 190 },
   { key: "Sugar",         description: "Cinnamon Sugar",                           gramsPerCup: 200 },
   { key: "Sugar",         description: "Coconut Sugar",                            gramsPerCup: 154 },
   { key: "Sugar",         description: "Confectioner's Sugar",                     gramsPerCup: 125 },
   { key: "Sugar",         description: "Demerara Sugar",                           gramsPerCup: 220 },
   { key: "Sugar",         description: "Granulated White Sugar",                   gramsPerCup: 200 },
   { key: "Sugar",         description: "Icing Sugar",                              gramsPerCup: 115 },
   { key: "Sugar",         description: "Maple Sugar",                              gramsPerCup: 156 },
   { key: "Sugar",         description: "Powdered Sugar",                           gramsPerCup: 125 },
   { key: "Sugar",         description: "Sugar",                                    gramsPerCup: 200 },
   { key: "Sugar",         description: "Superfine Sugar",                          gramsPerCup: 225 },
   { key: "Sugar",         description: "Unsifted Confectioner's Sugar",            gramsPerCup: 113 },
   { key: "Syrup",         description: "Agave Syrup",                              gramsPerCup: 336 },
   { key: "Syrup",         description: "Corn Syrup",                               gramsPerCup: 325 },
   { key: "Syrup",         description: "Golden Syrup",                             gramsPerCup: 350 },
   { key: "Syrup",         description: "Light Syrup",                              gramsPerCup: 320 },
   { key: "Syrup",         description: "Malt Barley Syrup",                        gramsPerCup: 336 },
   { key: "Syrup",         description: "Malt Syrup",                               gramsPerCup: 344 },
   { key: "Syrup",         description: "Maple Syrup",                              gramsPerCup: 310 },
   { key: "Syrup",         description: "Simple Syrup",                             gramsPerCup: 320 },
   { key: "Syrup",         description: "Treacle Syrup",                            gramsPerCup: 350 },
   { key: "Tapioca",       description: "Dry Tapioca",                              gramsPerCup: 150 },
   { key: "Tea",           description: "Tea",                                      gramsPerCup:  75 },
   { key: "Toffee",        description: "Toffee Bits",                              gramsPerCup: 156 },
   { key: "Toffee",        description: "Toffee Chunks",                            gramsPerCup: 156 },
   { key: "Tomato",        description: "Paste Sauce Tomato",                       gramsPerCup: 225 },
   { key: "Tomato",        description: "Tomato Paste",                             gramsPerCup: 232 },
   { key: "Tomatoes",      description: "Canned Tomatoes",                          gramsPerCup: 225 },
   { key: "Tomatoes",      description: "Chopped Tomatoes",                         gramsPerCup: 159 },
   { key: "Tomatoes",      description: "Fresh Diced Tomatoes",                     gramsPerCup: 200 },
   { key: "Tomatoes",      description: "Sun-Dried Tomatoes",                       gramsPerCup:  55 },
   { key: "Tomatoes",      description: "Tomatoes Packed in Tomato Juice",          gramsPerCup: 240 },
   { key: "Toppings",      description: "Strawberry Toppings",                      gramsPerCup: 340 },
   { key: "Tuna",          description: "Canned Tuna",                              gramsPerCup: 199 },
   { key: "Turkey",        description: "Diced Roasted Turkey",                     gramsPerCup: 140 },
   { key: "Turkey",        description: "Shredded Cooked Turkey",                   gramsPerCup: 125 },
   { key: "Turmeric",      description: "Ground Turmeric",                          gramsPerCup: 138 },
   { key: "Turnips",       description: "Diced Cooked Turnips",                     gramsPerCup: 200 },
   { key: "Turnips",       description: "Diced Raw Turnips",                        gramsPerCup: 150 },
   { key: "Turnips",       description: "Mashed Cooked Turnips",                    gramsPerCup: 200 },
   { key: "Turnips",       description: "Sliced Raw Turnips",                       gramsPerCup: 150 },
   { key: "Vanilla",       description: "Vanilla Extract",                          gramsPerCup: 240 },
   { key: "Veal",          description: "Cooked Diced Veal",                        gramsPerCup: 150 },
   { key: "Veal",          description: "Raw Minced Ground Veal",                   gramsPerCup: 225 },
   { key: "Vegetables",    description: "Frozen Diced Vegetables",                  gramsPerCup: 150 },
   { key: "Venison",       description: "Ground Raw Venison",                       gramsPerCup: 225 },
   { key: "Venison",       description: "Minced Raw Venison",                       gramsPerCup: 225 },
   { key: "Vinegar",       description: "Distilled Vinegar",                        gramsPerCup: 240 },
   { key: "Wafers",        description: "Crushed Vanilla Wafers",                   gramsPerCup: 163 },
   { key: "Walnuts",       description: "Chopped Walnuts",                          gramsPerCup: 115 },
   { key: "Walnuts",       description: "Ground Walnuts",                           gramsPerCup:  87 },
   { key: "Walnuts",       description: "Shelled Chopped Walnuts",                  gramsPerCup: 125 },
   { key: "Walnuts",       description: "Shelled Halved Walnuts",                   gramsPerCup: 100 },
   { key: "Walnuts",       description: "Shelled Walnuts",                          gramsPerCup: 120 },
   { key: "Walnuts",       description: "Whole Walnuts",                            gramsPerCup: 128 },
   { key: "Water",         description: "Water",                                    gramsPerCup: 240 },
   { key: "Wheat",         description: "Cooked Bulgar Wheat",                      gramsPerCup: 250 },
   { key: "Wheat",         description: "Cracked Wheat",                            gramsPerCup: 135 },
   { key: "Wheat",         description: "Farina Wheat",                             gramsPerCup: 179 },
   { key: "Wheat",         description: "Raw Bulgur Wheat",                         gramsPerCup: 225 },
   { key: "Wheat",         description: "Semolina Wheat",                           gramsPerCup: 200 },
   { key: "Wheat",         description: "Wheat Bran",                               gramsPerCup:  64 },
   { key: "Wheat",         description: "Wheat Germ",                               gramsPerCup: 120 },
   { key: "Yam",           description: "Cubed Cooked Yam",                         gramsPerCup: 200 },
   { key: "Yam",           description: "Cubed Raw Yam",                            gramsPerCup: 150 },
   { key: "Yam",           description: "Sliced Cooked Yam",                        gramsPerCup: 200 },
   { key: "Yam",           description: "Sliced Raw Yam",                           gramsPerCup: 150 },
   { key: "Yeast",         description: "Active Dry Yeast",                         gramsPerCup: 153 },
   { key: "Yeast",         description: "Instant Yeast",                            gramsPerCup: 144 },
   { key: "Yogurt",        description: "Yogurt",                                   gramsPerCup: 240 },
   { key: "Zucchini",      description: "Diced Zucchini",                           gramsPerCup: 175 },
   { key: "Zucchini",      description: "Shredded Zucchini",                        gramsPerCup: 135 },
   { key: "Zucchini",      description: "Sliced Zucchini",                          gramsPerCup: 150 },
   ];
